name: Pipeline
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ServerSide
          node testAllQuotes.js
      
  Deploy-EC2-TEST:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS-CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
      
    - name: open-firewall
      uses: ferulisses/aws-manage-firewall-action@v1.2
      with:
        rule-id: 'sg-0814d306e4384f621'
        protocol: tcp
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-2'

    - name: terminate-All-TEST-Instances
      run: |
        export Environment="Test"
        ./.github/scripts/TerminateEC2Instances.sh

    - name: zip-folders-and-push-to-S3
      run: ./.github/scripts/ZipFoldersAndPushToS3.sh 
      
    - name: run-LaunchEC2-TEST
      run: |
        export Environment="Test"
        export SecurityGroup="sg-0814d306e4384f621"
        ./.github/scripts/LaunchEC2.sh

    - name: run-a-system-test
      uses: wei/curl@master
      with:
        args: http://${{env.EC2_PUBLIC_IP}}:3000/search?search_string=money

    - name: export-IP-EC2
      run: ./.github/scripts/Get-IP.sh

    - name: export-InstanceID-EC2
      run: ./.github/scripts/Get-InstanceID.sh
      

  PromoteTo-PROD:
      needs: Deploy-EC2-TEST
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS-CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

    #disacociate IP address from old Prod EC2 instance

    #Terminate all PROD Instances
    - name: terminate-All-PROD-Instances
      run: |
        export Environment="Prod"
        ./.github/scripts/TerminateEC2Instances.sh

    #change EC2 name to Prod server
    - name: rename-Test-EC2-Instance
      run: aws ec2 create-tags --resources ${{env.EC2_INSTANCE_ID}} --tag "Key=Name,Value=Prod_Quote_Server"

    #change security group to prod security group
    - name: change-SG-Of-TestInstance
      run:  | 
          aws ec2 modify-instance-attribute \
          --instance-id ${{env.EC2_INSTANCE_ID}} \
          --groups sg-0329da65af5ecbc8b

    #associate IP address to new EC2 instance
    - name: associate-elastic-IP-to-new-Instance
      run: aws ec2 associate-address --instance-id ${{env.EC2_INSTANCE_ID}} --public-ip 3.20.27.183