name: Pipeline
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ServerSide
          node testAllQuotes.js
      
  Configure-CLI-And-Deploy-EC2:
    #needs: run-unit-tests
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS-CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #aws-region: us-east-2
        #role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        #role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
        #role-duration-seconds: 1200
        #role-session-name: MySessionName
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
      
    - name: run-script
      run: ./.github/scripts/LaunchEC2.sh
