name: Demo 2 Pipeline
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ServerSide
          node testAllQuotes.js
